### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by stefanpenner** [HappySale/ember-cli-cloudinary-images#2]
https://github.com/ember-cli/ember-cli/issues/4199

**Comment by stefanpenner** [comment]
like: https://github.com/ember-cli/ember-cli/commit/6ac18227ea571988fa9d9950e9a1051fdd990c7c

**Comment by oriSomething** [comment]
but i actually see that `tmp/` exist in `.npmignore`
https://github.com/HappySale/ember-cli-cloudinary-images/blob/master/.npmignore#L3

am i missing something?

**Comment by stefanpenner** [comment]
Has there been a release since then?

**Comment by oriSomething** [comment]
yep you right. i did upgrade some stuff including this, but haven't release version since.
new version will be release sooner, now.
thanks!

**Comment by oriSomething** [comment]
published new version to NPM.

thanks!
